import { jsPDF } from "jspdf";
import { svgToPngDataUrl } from "./exportChart";
import { SOURCES } from "./sources";

export interface EvidenceStat {
  label: string;
  value: string;
}

export interface EvidenceSnapshotInput {
  title: string;
  subtitle?: string;
  chartSvg: SVGSVGElement;
  stats: EvidenceStat[];
  sourceKeys: (keyof typeof SOURCES)[];
  caveat: string;
}

const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 portrait, mm

function today(): string {
  return new Date().toLocaleDateString("en-MY", { year: "numeric", month: "long", day: "numeric" });
}

/**
 * A one-page, citable PDF for a single finding: the chart itself (rasterized
 * via the same zero-dep svgToPngDataUrl already used for PNG export), the
 * exact statistics shown on screen, a formatted citation per source (from
 * the existing SOURCES registry — no new provenance data invented here),
 * and whatever caveat text the caller already displays on screen (e.g.
 * CorrelationCaveat's copy). Meant to be pasted into or attached to a
 * paper/grant without manual screenshotting.
 */
export async function buildEvidenceSnapshotPdf(input: EvidenceSnapshotInput): Promise<void> {
  const rect = input.chartSvg.getBoundingClientRect();
  const pngDataUrl = await svgToPngDataUrl(input.chartSvg);

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(input.title, MARGIN, y);
  y += 8;

  if (input.subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(90);
    const subtitleLines = doc.splitTextToSize(input.subtitle, PAGE_WIDTH - MARGIN * 2);
    doc.text(subtitleLines, MARGIN, y);
    y += subtitleLines.length * 5 + 3;
    doc.setTextColor(0);
  }

  const imgWidth = PAGE_WIDTH - MARGIN * 2;
  const imgHeight = (rect.height / rect.width) * imgWidth;
  doc.addImage(pngDataUrl, "PNG", MARGIN, y, imgWidth, imgHeight);
  y += imgHeight + 8;

  if (input.stats.length > 0) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Statistics", MARGIN, y);
    y += 6;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    for (const stat of input.stats) {
      doc.text(`${stat.label}: ${stat.value}`, MARGIN, y);
      y += 5.5;
    }
    y += 3;
  }

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Sources", MARGIN, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  for (const key of input.sourceKeys) {
    const s = SOURCES[key];
    if (!s) continue;
    const citation = `${s.org}. "${s.label}." Geography: ${s.geography}. Unit: ${s.unit}. Last updated: ${s.lastUpdated}. Accessed ${today()}. ${s.url}`;
    const lines = doc.splitTextToSize(citation, PAGE_WIDTH - MARGIN * 2);
    doc.text(lines, MARGIN, y);
    y += lines.length * 4.5 + 2;
  }
  y += 3;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Methodology & caveats", MARGIN, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90);
  const caveatLines = doc.splitTextToSize(input.caveat, PAGE_WIDTH - MARGIN * 2);
  doc.text(caveatLines, MARGIN, y);
  y += caveatLines.length * 4.5 + 6;
  doc.setTextColor(0);

  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text(
    `Generated by Malaysia Health Equity Observatory (MY-HEO) on ${today()}. This is a downloaded snapshot, not a live view — verify current figures against the dashboard or the cited source directly before use in publication.`,
    MARGIN,
    287
  );

  const filename = `${input.title.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}_evidence_snapshot.pdf`;
  doc.save(filename);
}
