// Route -> processed data files the page reads. Used for the per-page "data as of" line.
// Kept identical to netlify-chat/netlify/edge-functions/lib/pageData.ts (which grounds the AI assistant in the
// same files); a unit test checks every name here exists in public/data and in INVENTORY_MAP, so a rename can't
// silently break the line. /explorer, /data-gaps and /methodology are inventory pages and have no entry.
export const PAGE_DATA_FILES: Record<string, string[]> = {
  "/": [
    "socioeconomic_national.json",
    "socioeconomic_state.json",
    "healthcare_access_national.json",
    "population_state.json",
    "healthcare_access_state.json",
  ],
  "/map": [
    "socioeconomic_state.json",
    "healthcare_access_state.json",
    "health_outcomes_state.json",
    "fertility_state.json",
    "deaths_district_sex.json",
    "births_district_sex.json",
    "forest_reserve_state.json",
    "water_consumption_state.json",
    "water_production_state.json",
  ],
  "/socioeconomic": [
    "socioeconomic_national.json",
    "socioeconomic_state.json",
    "socioeconomic_district.json",
    "health_outcomes_state.json",
    "hies_percentile_national.json",
    "sanitation_access_state.json",
    "water_access_state.json",
    "water_access_national.json",
    "electricity_access_region.json",
    "sanitation_access_national.json",
  ],
  "/health-outcomes": [
    "health_outcomes_state.json",
    "immunisation_national.json",
    "nutrition_national.json",
    "covid_state.json",
    "health_programmes_state.json",
    "pekab40_screenings_daily_state.json",
    "hiv_incidence_national.json",
    "deaths_ethnicity_state.json",
    "covid_national.json",
  ],
  "/healthcare-access": [
    "healthcare_access_national.json",
    "healthcare_access_state.json",
    "healthcare_access_district_2022.json",
    "population_state.json",
  ],
  "/financing": ["mnha_national.json"],
  "/environment": [
    "forest_reserve_national.json",
    "forest_reserve_state.json",
    "water_consumption_state.json",
    "water_production_state.json",
    "air_pollution_national.json",
    "ghg_emissions_national.json",
    "water_pollution_basin_national.json",
    "electricity_consumption_national.json",
    "electricity_supply_national.json",
  ],
  "/population": [
    "population_state.json",
    "population_district.json",
    "population_parlimen.json",
    "population_dun.json",
    "marriages_national.json",
    "fertility_state.json",
    "nutrition_national.json",
  ],
  "/determinants": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "socioeconomic_state.json",
    "nhms_ncd_state.json",
    "nhms_adolescent_mental_health_state.json",
    "sanitation_access_state.json",
    "water_access_state.json",
    "marriages_state.json",
    "fertility_state.json",
    "health_programmes_state.json",
    "forest_reserve_state.json",
    "water_consumption_state.json",
    "water_production_state.json",
    "air_pollution_national.json",
    "electricity_consumption_national.json",
    "electricity_supply_national.json",
    "ghg_emissions_national.json",
    "water_pollution_basin_national.json",
  ],
  "/matrix": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "socioeconomic_state.json",
    "nhms_ncd_state.json",
    "nhms_adolescent_mental_health_state.json",
    "sanitation_access_state.json",
    "water_access_state.json",
    "marriages_state.json",
    "fertility_state.json",
    "health_programmes_state.json",
    "forest_reserve_state.json",
    "water_consumption_state.json",
    "water_production_state.json",
  ],
  "/trends": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "socioeconomic_state.json",
    "nhms_ncd_state.json",
    "nhms_adolescent_mental_health_state.json",
    "sanitation_access_state.json",
    "water_access_state.json",
    "marriages_state.json",
    "fertility_state.json",
    "health_programmes_state.json",
    "forest_reserve_state.json",
    "water_consumption_state.json",
    "water_production_state.json",
    "air_pollution_national.json",
    "ghg_emissions_national.json",
    "water_pollution_basin_national.json",
    "electricity_consumption_national.json",
    "electricity_supply_national.json",
  ],
  "/analytics": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "socioeconomic_state.json",
    "population_state.json",
  ],
  "/state-matrix": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "socioeconomic_state.json",
    "nhms_ncd_state.json",
    "nhms_adolescent_mental_health_state.json",
    "sanitation_access_state.json",
    "water_access_state.json",
    "marriages_state.json",
    "fertility_state.json",
    "health_programmes_state.json",
    "forest_reserve_state.json",
    "water_consumption_state.json",
    "water_production_state.json",
  ],
  "/priority-areas": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "socioeconomic_state.json",
    "health_programmes_state.json",
    "nhms_ncd_state.json",
    "sanitation_access_state.json",
    "water_access_state.json",
  ],
  "/research-opportunities": [
    "health_outcomes_state.json",
    "healthcare_access_state.json",
    "fertility_state.json",
    "nhms_adolescent_mental_health_state.json",
    "nhms_ncd_state.json",
    "socioeconomic_state.json",
  ],
};
