/**
 * Central provenance registry. Every indicator shown in the dashboard must
 * cite its source (per project requirement) — components look up their
 * indicator key here and render a <SourceNote>. Keep this in sync with
 * data/inventory/dataset_inventory.json (the machine-readable version used
 * by the Data Explorer / Methodology pages).
 */
export interface SourceInfo {
  label: string;
  org: string;
  url: string;
  geography: string;
  unit: string;
  lastUpdated: string;
}

export const SOURCES: Record<string, SourceInfo> = {
  income: {
    label: "Household Income",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/hh_income_state",
    geography: "National / State / District",
    unit: "RM per month",
    lastUpdated: "2025-12-31",
  },
  poverty: {
    label: "Poverty Rate",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/hh_poverty_state",
    geography: "National / State / District",
    unit: "%",
    lastUpdated: "2025-12-31",
  },
  gini: {
    label: "Gini Coefficient",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/hh_inequality_state",
    geography: "National / State / District",
    unit: "index (0–1)",
    lastUpdated: "2025-12-31",
  },
  amenities: {
    label: "Access to Basic Amenities",
    org: "Department of Statistics Malaysia (DOSM), from HIES",
    url: "https://data.gov.my/data-catalogue/hh_access_amenities",
    geography: "State / District (2022)",
    unit: "%",
    lastUpdated: "2024-09-01",
  },
  hospital_beds: {
    label: "Hospital Beds",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/hospital_beds",
    geography: "National / State / District",
    unit: "count",
    lastUpdated: "2024-09-01",
  },
  healthcare_staff: {
    label: "Healthcare Staff",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/healthcare_staff",
    geography: "National / State",
    unit: "count",
    lastUpdated: "2024-09-01",
  },
  deaths: {
    label: "Deaths",
    org: "National Registration Department / DOSM",
    url: "https://data.gov.my/data-catalogue/deaths_state",
    geography: "National / State",
    unit: "count, per 1,000 population",
    lastUpdated: "2025-10-16",
  },
  maternal_deaths: {
    label: "Maternal Deaths",
    org: "National Registration Department / DOSM",
    url: "https://data.gov.my/data-catalogue/deaths_maternal_state",
    geography: "National / State",
    unit: "per 100,000 live births",
    lastUpdated: "2025-10-16",
  },
  early_childhood_deaths: {
    label: "Early Childhood Deaths",
    org: "National Registration Department / DOSM",
    url: "https://data.gov.my/data-catalogue/deaths_early_childhood_state",
    geography: "State",
    unit: "count / rate (varies by sub-type)",
    lastUpdated: "2025-10-16",
  },
  births: {
    label: "Live Births",
    org: "National Registration Department / DOSM",
    url: "https://data.gov.my/data-catalogue/births_annual_state",
    geography: "National / State",
    unit: "count, per 1,000 population",
    lastUpdated: "2025-10-16",
  },
  immunisation: {
    label: "Infant Immunisation Coverage",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/infant_immunisation",
    geography: "National",
    unit: "%",
    lastUpdated: "2024-11-20",
  },
  nutrition: {
    label: "Nutritional Status of Children Under 5",
    org: "Ministry of Health Malaysia (NHMS)",
    url: "https://data.gov.my/data-catalogue/nutrition_children_sex",
    geography: "National",
    unit: "%",
    lastUpdated: "2024-09-01",
  },
  std: {
    label: "Sexually Transmitted Diseases",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/std_state",
    geography: "State",
    unit: "cases, per 100,000 population",
    lastUpdated: "2024-09-01",
  },
  nhms_ncd: {
    label: "NCD Risk Factor Prevalence (NHMS 2019)",
    org: "Institute for Public Health (IPH), National Institutes of Health, Ministry of Health Malaysia",
    url: "https://iku.nih.gov.my/images/IKU/Document/REPORT/NHMS2019/Report_NHMS2019-NCD.pdf",
    geography: "National / State",
    unit: "% (weighted survey estimate, with 95% CI)",
    lastUpdated: "2020 (survey year 2019)",
  },
  nhms_adolescent_mental_health: {
    label: "Adolescent Depression / Anxiety / Stress (NHMS 2017, DASS-21)",
    org: "Institute for Public Health (IPH), National Institutes of Health, Ministry of Health Malaysia",
    url: "https://iku.nih.gov.my/images/IKU/Document/REPORT/NHMS2017/MHSReportNHMS2017.pdf",
    geography: "National / State",
    unit: "% (weighted survey estimate, with 95% CI) — secondary-school students aged 13–17, NOT adults",
    lastUpdated: "2017 (survey year 2017)",
  },
  population: {
    label: "Population",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/population_state",
    geography: "National / State / District",
    unit: "persons",
    lastUpdated: "2026-07-31",
  },
  census: {
    label: "Census Population (historical)",
    org: "Department of Statistics Malaysia (DOSM), GitHub open-data mirror",
    url: "https://github.com/dosm-malaysia/data-open",
    geography: "District",
    unit: "persons",
    lastUpdated: "2020 census round",
  },
  boundaries: {
    label: "Administrative Boundaries",
    org: "Department of Statistics Malaysia (DOSM), GitHub open-data mirror",
    url: "https://github.com/dosm-malaysia/data-open",
    geography: "State / District",
    unit: "geometry",
    lastUpdated: "current gazette",
  },
  population_electoral: {
    label: "Population by Parliamentary Constituency / DUN",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/population_parlimen",
    geography: "Parliamentary constituency / DUN — no boundary map available",
    unit: "thousands of persons",
    lastUpdated: "2024",
  },
  hies_percentile: {
    label: "Household Income by Percentile",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/hies_malaysia_percentile",
    geography: "National",
    unit: "RM",
    lastUpdated: "2024 (HIES survey)",
  },
  marriages: {
    label: "Marriages",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/marriages",
    geography: "National / State",
    unit: "count; rate per 1,000 population",
    lastUpdated: "2022",
  },
  fertility: {
    label: "Fertility Rate",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/fertility_state",
    geography: "State",
    unit: "TFR (births per woman); ASFR (per 1,000 women)",
    lastUpdated: "2024",
  },
  health_programmes: {
    label: "Health Programme Participation (blood donation, organ pledges, PeKa B40)",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/blood_donations_state",
    geography: "State",
    unit: "count (annual sum of daily source values)",
    lastUpdated: "ongoing (daily source, latest year partial)",
  },
  covid: {
    label: "COVID-19 Cases and Deaths",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/covid_cases",
    geography: "National / State",
    unit: "count",
    lastUpdated: "ongoing (daily source, latest year partial)",
  },
  mnha: {
    label: "National Health Accounts (Health Expenditure)",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/mnha",
    geography: "National",
    unit: "RM",
    lastUpdated: "2022",
  },
  sanitation: {
    label: "Basic Sanitation Access",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/sanitation_access",
    geography: "National / State",
    unit: "%",
    lastUpdated: "2022",
  },
  water: {
    label: "Basic Water Access",
    org: "Department of Statistics Malaysia (DOSM)",
    url: "https://data.gov.my/data-catalogue/water_access",
    geography: "National / State, urban / rural",
    unit: "%",
    lastUpdated: "2022",
  },
  electricity: {
    label: "Household Electricity Access",
    org: "Energy Commission Malaysia",
    url: "https://data.gov.my/data-catalogue/electricity_access",
    geography: "4 utility-operator regions — not the 16-state schema",
    unit: "count of households",
    lastUpdated: "2021",
  },
  pekab40_daily: {
    label: "PeKa B40 Health Screenings (daily)",
    org: "Ministry of Health Malaysia",
    url: "https://data.gov.my/data-catalogue/pekab40_screenings_state",
    geography: "State",
    unit: "count (daily)",
    lastUpdated: "ongoing (daily source)",
  },
  nutrition_strata: {
    label: "Nutritional Status of Children Under 5 (Urban / Rural)",
    org: "Ministry of Health Malaysia (NHMS)",
    url: "https://data.gov.my/data-catalogue/nutrition_children_strata",
    geography: "National",
    unit: "%",
    lastUpdated: "2019",
  },
  hiv_incidence: {
    label: "HIV Incidence (SDG 3.3.1)",
    org: "Ministry of Health Malaysia",
    url: "https://open.dosm.gov.my/data-catalogue/sdg_03-3-1",
    geography: "National",
    unit: "per 1,000 uninfected population",
    lastUpdated: "2022",
  },
  stillbirths: {
    label: "Stillbirths",
    org: "National Registration Department / DOSM",
    url: "https://open.dosm.gov.my/data-catalogue/stillbirths_state",
    geography: "State",
    unit: "per 1,000 total births",
    lastUpdated: "2024",
  },
  deaths_ethnicity: {
    label: "Deaths by Sex & Ethnicity",
    org: "National Registration Department / DOSM",
    url: "https://open.dosm.gov.my/data-catalogue/deaths_sex_ethnic_state",
    geography: "State",
    unit: "count",
    lastUpdated: "2024",
  },
  deaths_district: {
    label: "Deaths by District & Sex",
    org: "National Registration Department / DOSM",
    url: "https://open.dosm.gov.my/data-catalogue/deaths_district_sex",
    geography: "District",
    unit: "per 1,000 population",
    lastUpdated: "2024",
  },
  births_district: {
    label: "Live Births by District & Sex",
    org: "National Registration Department / DOSM",
    url: "https://open.dosm.gov.my/data-catalogue/births_district_sex",
    geography: "District",
    unit: "per 1,000 population",
    lastUpdated: "2024",
  },
};
